export const KYC_OPTIONS = [
  { label: "Aadhar Card", src: "/id-proof/aadhaar.png" },
  { label: "Passport", src: "/id-proof/passport.png" },
  { label: "Driving License", src: "/id-proof/driving-license.png" },
  { label: "Pan Card", src: "/id-proof/pan-card.png" },
  { label: "Voter ID", src: "/id-proof/voterId.png" },
  { label: "Other", src: "/id-proof/aadhaar.png" },
];

export const IDENTITY_BUTTONS = [
  "Person",
  "Student",
  "Name",
  "College",
  "Address",
];

export const DP_IDENTITY = [
  "Customer",
  "Employee",
  "Platform User",
  "App User",
  "Job Applicant",
  "Marketing Recipient",
  "Nominee",
  "Guardian",
  "Parent",
  "Legal",
];

export const PRIORITY_OPTIONS = [
  { value: "low", label: "Low" },
  { value: "medium", label: "Medium" },
  { value: "high", label: "High" },
];

export const RELATED_REQUEST_TYPE = [
  { value: "update_data", label: "Correct / Update My Data" },
  { value: "delete_data", label: "Delete My Data" },
];

export const REQUEST_TYPE_OPTIONS = [
  { value: "update_data", label: "Correct / Update My Data" },
  { value: "delete_data", label: "Delete My Data" },
];

export const COUNTRY_OPTIONS = [
  { label: "India", value: "india" },
  { label: "Afghanistan", value: "afghanistan" },
  { label: "Albania", value: "albania" },
  { label: "Algeria", value: "algeria" },
  { label: "Andorra", value: "andorra" },
  { label: "Angola", value: "angola" },
  { label: "Antigua and Barbuda", value: "antigua and barbuda" },
  { label: "Argentina", value: "argentina" },
  { label: "Armenia", value: "armenia" },
  { label: "Australia", value: "australia" },
  { label: "Austria", value: "austria" },
  { label: "Azerbaijan", value: "azerbaijan" },
  { label: "Bahamas", value: "bahamas" },
  { label: "Bahrain", value: "bahrain" },
  { label: "Bangladesh", value: "bangladesh" },
  { label: "Barbados", value: "barbados" },
  { label: "Belarus", value: "belarus" },
  { label: "Belgium", value: "belgium" },
  { label: "Belize", value: "belize" },
  { label: "Benin", value: "benin" },
  { label: "Bhutan", value: "bhutan" },
  { label: "Bolivia", value: "bolivia" },
  { label: "Bosnia and Herzegovina", value: "bosnia and herzegovina" },
  { label: "Botswana", value: "botswana" },
  { label: "Brazil", value: "brazil" },
  { label: "Brunei", value: "brunei" },
  { label: "Bulgaria", value: "bulgaria" },
  { label: "Burkina Faso", value: "burkina faso" },
  { label: "Burundi", value: "burundi" },
  { label: "Cabo Verde", value: "cabo verde" },
  { label: "Cambodia", value: "cambodia" },
  { label: "Cameroon", value: "cameroon" },
  { label: "Canada", value: "canada" },
  { label: "Central African Republic", value: "central african republic" },
  { label: "Chad", value: "chad" },
  { label: "Chile", value: "chile" },
  { label: "China", value: "china" },
  { label: "Colombia", value: "colombia" },
  { label: "Comoros", value: "comoros" },
  { label: "Congo (Congo-Brazzaville)", value: "congo" },
  { label: "Costa Rica", value: "costa rica" },
  { label: "Croatia", value: "croatia" },
  { label: "Cuba", value: "cuba" },
  { label: "Cyprus", value: "cyprus" },
  { label: "Czechia (Czech Republic)", value: "czechia" },
  { label: "Denmark", value: "denmark" },
  { label: "Djibouti", value: "djibouti" },
  { label: "Dominica", value: "dominica" },
  { label: "Dominican Republic", value: "dominican republic" },
  { label: "Ecuador", value: "ecuador" },
  { label: "Egypt", value: "egypt" },
  { label: "El Salvador", value: "el salvador" },
  { label: "Equatorial Guinea", value: "equatorial guinea" },
  { label: "Eritrea", value: "eritrea" },
  { label: "Estonia", value: "estonia" },
  { label: "Eswatini (Swaziland)", value: "eswatini" },
  { label: "Ethiopia", value: "ethiopia" },
  { label: "Fiji", value: "fiji" },
  { label: "Finland", value: "finland" },
  { label: "France", value: "france" },
  { label: "Gabon", value: "gabon" },
  { label: "Gambia", value: "gambia" },
  { label: "Georgia", value: "georgia" },
  { label: "Germany", value: "germany" },
  { label: "Ghana", value: "ghana" },
  { label: "Greece", value: "greece" },
  { label: "Grenada", value: "grenada" },
  { label: "Guatemala", value: "guatemala" },
  { label: "Guinea", value: "guinea" },
  { label: "Guinea-Bissau", value: "guinea-bissau" },
  { label: "Guyana", value: "guyana" },
  { label: "Haiti", value: "haiti" },
  { label: "Honduras", value: "honduras" },
  { label: "Hungary", value: "hungary" },
  { label: "Iceland", value: "iceland" },
  { label: "Indonesia", value: "indonesia" },
  { label: "Iran", value: "iran" },
  { label: "Iraq", value: "iraq" },
  { label: "Ireland", value: "ireland" },
  { label: "Israel", value: "israel" },
  { label: "Italy", value: "italy" },
  { label: "Jamaica", value: "jamaica" },
  { label: "Japan", value: "japan" },
  { label: "Jordan", value: "jordan" },
  { label: "Kazakhstan", value: "kazakhstan" },
  { label: "Kenya", value: "kenya" },
  { label: "Kiribati", value: "kiribati" },
  { label: "Kuwait", value: "kuwait" },
  { label: "Kyrgyzstan", value: "kyrgyzstan" },
  { label: "Laos", value: "laos" },
  { label: "Latvia", value: "latvia" },
  { label: "Lebanon", value: "lebanon" },
  { label: "Lesotho", value: "lesotho" },
  { label: "Liberia", value: "liberia" },
  { label: "Libya", value: "libya" },
  { label: "Liechtenstein", value: "liechtenstein" },
  { label: "Lithuania", value: "lithuania" },
  { label: "Luxembourg", value: "luxembourg" },
  { label: "Madagascar", value: "madagascar" },
  { label: "Malawi", value: "malawi" },
  { label: "Malaysia", value: "malaysia" },
  { label: "Maldives", value: "maldives" },
  { label: "Mali", value: "mali" },
  { label: "Malta", value: "malta" },
  { label: "Marshall Islands", value: "marshall islands" },
  { label: "Mauritania", value: "mauritania" },
  { label: "Mauritius", value: "mauritius" },
  { label: "Mexico", value: "mexico" },
  { label: "Micronesia", value: "micronesia" },
  { label: "Moldova", value: "moldova" },
  { label: "Monaco", value: "monaco" },
  { label: "Mongolia", value: "mongolia" },
  { label: "Montenegro", value: "montenegro" },
  { label: "Morocco", value: "morocco" },
  { label: "Mozambique", value: "mozambique" },
  { label: "Myanmar (Burma)", value: "myanmar" },
  { label: "Namibia", value: "namibia" },
  { label: "Nauru", value: "nauru" },
  { label: "Nepal", value: "nepal" },
  { label: "Netherlands", value: "netherlands" },
  { label: "New Zealand", value: "new zealand" },
  { label: "Nicaragua", value: "nicaragua" },
  { label: "Niger", value: "niger" },
  { label: "Nigeria", value: "nigeria" },
  { label: "North Korea", value: "north korea" },
  { label: "North Macedonia", value: "north macedonia" },
  { label: "Norway", value: "norway" },
  { label: "Oman", value: "oman" },
  { label: "Pakistan", value: "pakistan" },
  { label: "Palau", value: "palau" },
  { label: "Palestine State", value: "palestine state" },
  { label: "Panama", value: "panama" },
  { label: "Papua New Guinea", value: "papua new guinea" },
  { label: "Paraguay", value: "paraguay" },
  { label: "Peru", value: "peru" },
  { label: "Philippines", value: "philippines" },
  { label: "Poland", value: "poland" },
  { label: "Portugal", value: "portugal" },
  { label: "Qatar", value: "qatar" },
  { label: "Romania", value: "romania" },
  { label: "Russia", value: "russia" },
  { label: "Rwanda", value: "rwanda" },
  { label: "Saint Kitts and Nevis", value: "saint kitts and nevis" },
  { label: "Saint Lucia", value: "saint lucia" },
  {
    label: "Saint Vincent and the Grenadines",
    value: "saint vincent and the grenadines",
  },
  { label: "Samoa", value: "samoa" },
  { label: "San Marino", value: "san marino" },
  { label: "Sao Tome and Principe", value: "sao tome and principe" },
  { label: "Saudi Arabia", value: "saudi arabia" },
  { label: "Senegal", value: "senegal" },
  { label: "Serbia", value: "serbia" },
  { label: "Seychelles", value: "seychelles" },
  { label: "Sierra Leone", value: "sierra leone" },
  { label: "Singapore", value: "singapore" },
  { label: "Slovakia", value: "slovakia" },
  { label: "Slovenia", value: "slovenia" },
  { label: "Solomon Islands", value: "solomon islands" },
  { label: "Somalia", value: "somalia" },
  { label: "South Africa", value: "south africa" },
  { label: "South Korea", value: "south korea" },
  { label: "South Sudan", value: "south sudan" },
  { label: "Spain", value: "spain" },
  { label: "Sri Lanka", value: "sri lanka" },
  { label: "Sudan", value: "sudan" },
  { label: "Suriname", value: "suriname" },
  { label: "Sweden", value: "sweden" },
  { label: "Switzerland", value: "switzerland" },
  { label: "Syria", value: "syria" },
  { label: "Tajikistan", value: "tajikistan" },
  { label: "Tanzania", value: "tanzania" },
  { label: "Thailand", value: "thailand" },
  { label: "Timor-Leste", value: "timor-leste" },
  { label: "Togo", value: "togo" },
  { label: "Tonga", value: "tonga" },
  { label: "Trinidad and Tobago", value: "trinidad and tobago" },
  { label: "Tunisia", value: "tunisia" },
  { label: "Turkey", value: "turkey" },
  { label: "Turkmenistan", value: "turkmenistan" },
  { label: "Tuvalu", value: "tuvalu" },
  { label: "Uganda", value: "uganda" },
  { label: "Ukraine", value: "ukraine" },
  { label: "United Arab Emirates", value: "united arab emirates" },
  { label: "UK", value: "uk" },
  { label: "USA", value: "usa" },
  { label: "Uruguay", value: "uruguay" },
  { label: "Uzbekistan", value: "uzbekistan" },
  { label: "Vanuatu", value: "vanuatu" },
  { label: "Vatican City", value: "vatican city" },
  { label: "Venezuela", value: "venezuela" },
  { label: "Vietnam", value: "vietnam" },
  { label: "Yemen", value: "yemen" },
  { label: "Zambia", value: "zambia" },
  { label: "Zimbabwe", value: "zimbabwe" },
];

export const DP_TYPE_OPTIONS = [
  { value: "Customer", label: "Customer" },
  { value: "Employee", label: "Employee" },
  { value: "Platform User", label: "Platform User" },
  { value: "App User", label: "App User" },
  { value: "Job Applicant", label: "Job Applicant" },
  { value: "Marketing Recipient", label: "Marketing Recipient" },
  { value: "Nominee", label: "Nominee" },
  { value: "Guardian", label: "Guardian" },
  { value: "Parent", label: "Parent" },
  { value: "Legal", label: "Legal" },
];

export const CATEGORY_OPTIONS = [
  { value: "consent_related", label: "Consent-Related" },
  { value: "access_transparency", label: "Access & Transparency" },
  { value: "data_accuracy", label: "Data Accuracy & Rectification" },
  { value: "purpose_limitation", label: "Purpose Limitation / Misuse of Data" },
  { value: "data_retention", label: "Data Retention / Deletion" },
  { value: "grievance", label: "Grievance Handling Failures" },
  { value: "security", label: "Security / Data Breach" },
  { value: "cross_border", label: "Cross-Border / Third-Party Transfers" },
];

export const SUB_CATEGORY_OPTIONS = {
  consent_related: [
    {
      value: "Data collected without consent",
      label: "Data collected without consent",
    },
    {
      value: "Consent withdrawal ignored",
      label: "Consent withdrawal ignored",
    },
    { value: "Forced / bundled consent", label: "Forced / bundled consent" },
  ],
  access_transparency: [
    {
      value: "No response to access request",
      label: "No response to access request",
    },
    { value: "Unclear privacy policy", label: "Unclear privacy policy" },
    { value: "Unknown data recipients", label: "Unknown data recipients" },
  ],
  data_accuracy: [
    {
      value: "Incorrect personal data stored",
      label: "Incorrect personal data stored",
    },
    { value: "Refused to correct data", label: "Refused to correct data" },
    {
      value: "Outdated or merged records",
      label: "Outdated or merged records",
    },
  ],
  purpose_limitation: [
    {
      value: "Data used for marketing without consent",
      label: "Data used for marketing without consent",
    },
    {
      value: "Shared with third parties unexpectedly",
      label: "Shared with third parties unexpectedly",
    },
    {
      value: "Used beyond original purpose",
      label: "Used beyond original purpose",
    },
  ],
  data_retention: [
    { value: "Refused to delete data", label: "Refused to delete data" },
    { value: "Retaining data too long", label: "Retaining data too long" },
    { value: "Deleted data resurfaced", label: "Deleted data resurfaced" },
  ],
  grievance: [
    {
      value: "No response to previous grievance",
      label: "No response to previous grievance",
    },
    {
      value: "Grievance marked resolved without fix",
      label: "Grievance marked resolved without fix",
    },
    { value: "No escalation channel", label: "No escalation channel" },
  ],
  security: [
    { value: "Data leaked or breached", label: "Data leaked or breached" },
    { value: "Unauthorized access", label: "Unauthorized access" },
    {
      value: "Delay in breach notification",
      label: "Delay in breach notification",
    },
  ],
  cross_border: [
    {
      value: "Data sent overseas without notice",
      label: "Data sent overseas without notice",
    },
    {
      value: "Shared with unknown partners",
      label: "Shared with unknown partners",
    },
    {
      value: "No information on processors",
      label: "No information on processors",
    },
  ],
};

export const FORM_TEXT = {
  TITLE: "Data Rights",
  DESCRIPTION:
    "Provide details of your request so we can review and respond quickly.",
  PERSONAL_INFO: "Personal Information",
  IDENTITY_DETAILS: "Identity Details",
  REQUEST_INFO: "Request Information",
  KYC_VERIFICATION: "KYC Verification",
  UPLOAD_DOCS: "Upload Documents",
  NOTE: "Please Note",
  NOTE_TEXT:
    "Concur and its subsidiaries and affiliates can only action requests from individuals with a direct relationship to Concur or its subsidiaries and affiliates.",
  TERMS: "I agree to the Terms and Conditions and Privacy Policy.",
  SUBMIT_BUTTON: "Complete",
};

export const FILE_TYPES = ["pdf", "png", "jpg", "jpeg"];
