export const industryOptions = {
  Insurance: [
    "Customer Support",
    "Research & Development",
    "Technology",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Training & Development",
    "Product Management",
    "Innovation",
    "Marketing",
    "Operations",
    "Data Analytics & Science",
  ],
  Fintech: [
    "Marketing",
    "Operations",
    "Data Analytics & Science",
    "Customer Support",
    "Research & Development",
    "Technology",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Training & Development",
    "Product Management",
  ],
  Startup: [
    "Customer Support",
    "Data Analytics & Science",
    "Finance",
    "Human Resource",
    "Legal & Compliance",
    "Marketing",
    "Operations",
    "Product Management",
    "Quality Assurance",
    "Research & Development",
    "Technology",
    "Training & Development",
  ],
  "Online Gaming": [
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  "AR/VR": [
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  "Real Estate": [
    "Marketing",
    "Data Analytics & Science",
    "Customer Support",
    "Research & Development",
    "Technology",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
    "Operation",
  ],
  Pharmaceuticals: [
    "Customer Support",
    "Data Analytics & Science",
    "Finance",
    "Human Resource",
    "Legal & Compliance",
    "Marketing",
    "Operations",
    "Product Management",
    "Quality Assurance",
    "Research & Development",
    "Technology",
    "Training & Development",
  ],
  Marketing: [
    "Marketing",
    "Operations",
    "Data Analytics & Science",
    "Customer Support",
    "Research & Development",
    "Technology",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  Hospital: [
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Operations",
    "Marketing",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  "Hotels/Restaurants": [
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  Banking: [
    "Customer Support",
    "Data Analytics & Science",
    "Finance",
    "Human Resource",
    "Legal & Compliance",
    "Marketing",
    "Operations",
    "Product Management",
    "Quality Assurance",
    "Research & Development",
    "Technology",
    "Training & Development",
  ],
  NBFC: [
    "Customer Support",
    "Data Analytics & Science",
    "Finance",
    "Human Resource",
    "Legal & Compliance",
    "Marketing",
    "Operations",
    "Product Management",
    "Quality Assurance",
    "Research & Development",
    "Technology",
    "Training & Development",
  ],
  Education: [
    "Marketing",
    "Operations",
    "Data Analytics & Science",
    "Customer Support",
    "Research & Development",
    "Technology",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  "Marketing Research": [
    "Customer Support",
    "Data Analytics & Science",
    "Finance",
    "Human Resource",
    "Legal & Compliance",
    "Marketing",
    "Operations",
    "Product Management",
    "Quality Assurance",
    "Research & Development",
    "Technology",
    "Training & Development",
  ],
  "University/College": [
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  Logistics: [
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  "Music Industry": [
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Technology",
    "Research & Development",
    "Training & Development",
    "Product Management",
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  Airlines: [
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  HRMS: [
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  AgriTech: [
    "Data Analytics & Science",
    "Customer Support",
    "Finance",
    "Legal & Compliance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  "Fitness & Wellness": [
    "Data Analytics & Science",
    "Marketing",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  RetailTech: [
    "Data Analytics & Science",
    "Marketing",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  LegalTech: [
    "Data Analytics & Science",
    "Marketing",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  Automobile: [
    "Data Analytics & Science",
    "Marketing",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  Finance: [
    "Marketing",
    "Operations",
    "Customer Support",
    "Technology",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Training & Development",
    "Product Management",
    "Data Analytics & Science",
    "Quality Assurance",
    "Research & Development",
    "Supply Chain Management",
  ],
  "OTT Platforms": [
    "Customer Support",
    "Data Analytics & Science",
    "Finance",
    "Human Resource",
    "Legal & Compliance",
    "Marketing",
    "Operations",
    "Product Management",
    "Quality Assurance",
    "Research & Development",
    "Technology",
    "Training & Development",
  ],
  Healthcare: [
    "Customer Support",
    "Data Analytics & Science",
    "Finance",
    "Human Resource",
    "Legal & Compliance",
    "Marketing",
    "Operations",
    "Product Management",
    "Quality Assurance",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Patient Care and Treatment",
  ],
  "Social media": [
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  "Beauty & Cosmetics": [
    "Data Analytics & Science",
    "Marketing",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  Ecommerce: [
    "Marketing",
    "Operations",
    "Data Analytics & Science",
    "Customer Support",
    "Research & Development",
    "Technology",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
    "Supply Chain Management",
  ],
  FemTech: [
    "Customer Support",
    "Data Analytics & Science",
    "Finance",
    "Human Resource",
    "Legal & Compliance",
    "Marketing",
    "Operations",
    "Product Management",
    "Quality Assurance",
    "Research & Development",
    "Technology",
    "Training & Development",
  ],
  "Event Management": [
    "Data Analytics & Science",
    "Marketing",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  Shipping: [
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  "Media & Entertainment": [
    "Data Analytics & Science",
    "Marketing",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  Manufacturing: [
    "Data Analytics & Science",
    "Marketing",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  Consulting: [
    "Data Analytics & Science",
    "Marketing",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  "Food & Beverages": [
    "Customer Support",
    "Data Analytics & Science",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  "Fashion & Apparels": [
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
  Biotechnology: [
    "Data Analytics & Science",
    "Customer Support",
    "Legal & Compliance",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations",
    "Research & Development",
    "Technology",
    "Training & Development",
    "Product Management",
    "Quality Assurance",
  ],
};
