pg_database:
  query: "SELECT datname, datistemplate, datallowconn, datconnlimit, datfrozenxid, datminmxid, dattablespace, datacl FROM pg_database"
  metrics:
  - datname:
      usage: "LABEL"
      description: "Name of the database"
  - datistemplate:
      usage: "GAUGE"
      description: "Is this database a template?"
  - datallowconn:
      usage: "GAUGE"
      description: "Is this database allowing connections?"
  - datconnlimit:
      usage: "GAUGE"
      description: "Connection limit for this database (-1 means no limit)"
  - datfrozenxid:
      usage: "GAUGE"
      description: "Age of frozen transaction ID for this database"
  - datminmxid:
      usage: "GAUGE"
      description: "Minimum multixact ID for this database"

pg_stat_activity:
  query: "SELECT datname, state, count(*) as connections FROM pg_stat_activity WHERE datname IS NOT NULL GROUP BY datname, state"
  metrics:
  - datname:
      usage: "LABEL"
      description: "Name of the database"
  - state:
      usage: "LABEL"
      description: "Connection state"
  - connections:
      usage: "GAUGE"
      description: "Number of connections in this state"
