import pytest
from unittest.mock import AsyncMock, MagicMock
import asyncpg
from bson import ObjectId
from motor.motor_asyncio import AsyncIOMotorCollection
from app.crud.notice_notification_crud import NoticeNotificationCRUD
from datetime import datetime, timezone # Import datetime and timezone


# ------------------ MOCK COLLECTIONS AND POOL FIXTURES ------------------


@pytest.fixture
def mock_mongo_collection():
    """Mocked Mongo collection for notice notifications with correct async behavior."""
    collection = MagicMock(spec=AsyncIOMotorCollection)
    collection.insert_one = AsyncMock()
    return collection


@pytest.fixture
def mock_pg_conn():
    """Mocked asyncpg connection."""
    conn = MagicMock(spec=asyncpg.Connection)
    conn.execute = AsyncMock()
    conn.fetchrow = AsyncMock(return_value=None)
    conn.fetchval = AsyncMock(return_value=0)
    conn.fetch = AsyncMock(return_value=[])
    return conn


@pytest.fixture
def mock_pg_pool(mock_pg_conn):
    """Mocked asyncpg pool."""
    pool = MagicMock(spec=asyncpg.Pool)
    # Mock acquire context manager
    mock_ctx_mgr = AsyncMock()
    mock_ctx_mgr.__aenter__.return_value = mock_pg_conn
    pool.acquire.return_value = mock_ctx_mgr
    return pool


@pytest.fixture
def crud(mock_mongo_collection, mock_pg_pool):
    return NoticeNotificationCRUD(mock_mongo_collection, mock_pg_pool)


@pytest.fixture
def dummy_mongo_doc_data():
    return {
        "_id": ObjectId("60d0fe4f3460595e63456789"),
        "df_id": "df123",
        "notice_id": "notice123",
        "notification_type": "email",
        "status": "pending",
        "timestamp": "2023-01-01T10:00:00Z",
    }


@pytest.fixture
def dummy_pg_notification_data():
    return {
        "notification_id": "event123",
        "df_id": "df123",
        "is_notification_read": False,
        "is_notification_clicked": False,
        "timestamp": datetime(2023, 1, 1, 10, 0, 0, tzinfo=timezone.utc),
    }


# ------------------ TESTS ------------------


@pytest.mark.asyncio
async def test_insert_notice_notification(crud, mock_mongo_collection, dummy_mongo_doc_data):
    mock_insert_one_result = MagicMock()
    mock_insert_one_result.inserted_id = dummy_mongo_doc_data["_id"]
    mock_mongo_collection.insert_one.return_value = mock_insert_one_result

    document_to_insert = dummy_mongo_doc_data.copy()
    del document_to_insert["_id"] # _id is generated by MongoDB

    result = await crud.insert_notice_notification(document_to_insert)

    mock_mongo_collection.insert_one.assert_called_once_with(document_to_insert)
    assert result == mock_insert_one_result


@pytest.mark.asyncio
async def test_get_total_notice_notifications_count(crud, mock_pg_conn):
    df_id = "df123"
    mock_pg_conn.fetchval.return_value = 5

    result = await crud.get_total_notice_notifications_count(df_id)

    mock_pg_conn.fetchval.assert_called_once()
    assert "SELECT COUNT(*)" in mock_pg_conn.fetchval.call_args[0][0]
    assert mock_pg_conn.fetchval.call_args[0][1] == df_id
    assert result == 5


@pytest.mark.asyncio
async def test_get_notice_notifications(crud, mock_pg_conn, dummy_pg_notification_data):
    df_id = "df123"
    limit = 10
    skip = 0

    mock_pg_conn.fetch.return_value = [dummy_pg_notification_data.copy()]

    result = await crud.get_notice_notifications(df_id, limit, skip)

    mock_pg_conn.fetch.assert_called_once()
    assert "SELECT *" in mock_pg_conn.fetch.call_args[0][0]
    assert df_id in mock_pg_conn.fetch.call_args[0]
    assert limit in mock_pg_conn.fetch.call_args[0]
    assert skip in mock_pg_conn.fetch.call_args[0]
    assert len(result) == 1
    assert result[0] == dummy_pg_notification_data


@pytest.mark.asyncio
async def test_mark_notification_as_read(crud, mock_pg_conn):
    event_id = "event123"
    mock_pg_conn.execute.return_value = "UPDATE 1" # asyncpg execute returns status string

    result = await crud.mark_notification_as_read(event_id)

    mock_pg_conn.execute.assert_called_once()
    assert "UPDATE consent_notifications" in mock_pg_conn.execute.call_args[0][0]
    assert "SET is_notification_read = TRUE" in mock_pg_conn.execute.call_args[0][0]
    assert mock_pg_conn.execute.call_args[0][1] == event_id
    assert result == "UPDATE 1"


@pytest.mark.asyncio
async def test_mark_notification_as_clicked(crud, mock_pg_conn):
    event_id = "event123"
    mock_pg_conn.execute.return_value = "UPDATE 1" # asyncpg execute returns status string

    result = await crud.mark_notification_as_clicked(event_id)

    mock_pg_conn.execute.assert_called_once()
    assert "UPDATE consent_notifications" in mock_pg_conn.execute.call_args[0][0]
    assert "SET is_notification_clicked = TRUE" in mock_pg_conn.execute.call_args[0][0]
    assert mock_pg_conn.execute.call_args[0][1] == event_id
    assert result == "UPDATE 1"
